version: '3.7'
services:
    postgres:
        image: postgres:12.0
        restart: always
        environment:
          - POSTGRES_USER=admin@localhost.com
          - POSTGRES_PASSWORD=localhost
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
        networks:
          - local_network
networks:
  local_network:
    name: local_database_network